import { useMemo, useState } from "react";
import { Link } from "react-router-dom";

import styles from "./Pages.module.css";
import { Card } from "../components/primitives/Card.js";
import { PageContainer } from "../components/primitives/PageContainer.js";
import {
  SAMPLE_OBJECT_A,
  SAMPLE_OBJECT_B,
  applyPatch,
  patch,
  revertPatch,
  runQuickCompare,
} from "../lib/object-diff.js";

export function PatchPage() {
  const [source, setSource] = useState(() => JSON.stringify(SAMPLE_OBJECT_A, null, 2));
  const [target, setTarget] = useState(() => JSON.stringify(SAMPLE_OBJECT_B, null, 2));
  const [applied, setApplied] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const diffResult = useMemo(() => {
    try {
      const parsedA = JSON.parse(source) as unknown;
      const parsedB = JSON.parse(target) as unknown;
      setError(null);
      return runQuickCompare(parsedA, parsedB);
    } catch (caught) {
      setError(caught instanceof Error ? caught.message : "Invalid JSON input.");
      return null;
    }
  }, [source, target]);

  const operations = diffResult ? patch(diffResult) : [];

  function handleApply() {
    if (!diffResult) {
      return;
    }

    const parsed = JSON.parse(source) as unknown;
    const next = applyPatch(parsed, patch(diffResult));
    setApplied(JSON.stringify(next, null, 2));
  }

  function handleRevert() {
    if (!diffResult || !applied) {
      return;
    }

    const parsed = JSON.parse(applied) as unknown;
    const reverted = revertPatch(parsed, patch(diffResult));
    setApplied(JSON.stringify(reverted, null, 2));
  }

  return (
    <PageContainer
      compact
      description={
        <>
          Focused patch apply/revert. Use the <Link to="/">Object Diff Lab</Link> for optimize,
          validate, merge patch, and generated code.
        </>
      }
    >
      <div className={styles.splitGrid}>
        <Card description="Patch source" title="Object A">
          <textarea
            className={styles.jsonEditor}
            onChange={(e) => {
              setSource(e.target.value);
            }}
            rows={10}
            value={source}
          />
        </Card>
        <Card description="Patch target" title="Object B">
          <textarea
            className={styles.jsonEditor}
            onChange={(e) => {
              setTarget(e.target.value);
            }}
            rows={10}
            value={target}
          />
        </Card>
      </div>

      {error ? <p className={styles.errorText}>{error}</p> : null}

      <Card description="Operations generated by @jayoncode/object-diff" title="Generated patch">
        <pre className={styles.codeBlock}>{JSON.stringify(operations, null, 2)}</pre>
        <div className={styles.inlineList}>
          <button className={styles.pill} onClick={handleApply} type="button">
            Apply patch
          </button>
          <button className={styles.pill} onClick={handleRevert} type="button">
            Revert patch
          </button>
        </div>
      </Card>

      {applied ? (
        <Card description="Value after patch apply/revert" title="Applied result">
          <pre className={styles.codeBlock}>{applied}</pre>
        </Card>
      ) : null}
    </PageContainer>
  );
}
