/** Generated by scripts/sync-documentation.mjs — do not edit manually. */

export const browserLifecycleMeta = {
  version: "0.1.2",
  versionLabel: "v0.1.2",
  npmName: "@jayoncode/browser-lifecycle",
} as const;
