name: CI

on:
  push:
    branches:
      - main
      - master
      - develop
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    name: Continuous Integration
    uses: ./.github/workflows/quality.yml
    permissions:
      contents: read
    secrets: inherit
